public  class Calculation {
    public integer add(integer a, integer b){
        integer result = a + b;
         return result;
    }
    public integer subtract(integer a, integer b){
        integer result = a - b;
        return result;
    }
    
    public integer multiply(integer a, integer b){
        integer result = a * b;
        return result;
    }
    
    public integer divide(integer a, integer b){
        integer result = a / b;
        return result;
    }


    


    
    

}
