public  class MyCity {
    public void printString(integer a, string b){
        for(integer i = 1; i<=a; i++){
            system.debug(b+' '+i);
        }
    }







}
    //public string favoriteCafe;
    //public string favoritePark;
    //public string favoriteMall;
    //public string favoriteStore;

    //public string myFavoriteLocations(string sehir){
        //string sonuc = sehir;
        //system.debug(sonuc);
        //system.debug('The most beautuful cafe in my city:'+' '+ favoriteCafe+' ,most beatuful park:' +' '+favoritePark+' most beautitul mall:' +favoriteMall+' most beatuful store:'+ ' '+favoriteStore);
        
        //return sonuc;

        

    //}
//}
    
    //public void cityInformation(){
        //integer kurulusTarihi = 1776;
        //system.debug('Bulundugum ulkenin kurulus tarihi:'+' '+kurulusTarihi);
        //string gunDogumu = '06:45';
        //system.debug('Bulundugum lokasyonun gun dogumu saati:'+' '+gunDogumu);
        //extra
        //date currentTarih = date.today();
        //date otuzaltiAyOncesi = currentTarih.addMonths(-36);
        //system.debug(otuzaltiAyOncesi);
        //string nerede = 'Istanbul/Maslak Oto Sanayi';
        //string neYenir = 'Kokorec';
        //string neredeNeYenir = nerede +'de'+' '+ neYenir +' yenir.';
        //return neredeNeYenir;

        //public void stringMethod(){
            //string test = 'I am a Salesforce Developer';
            //boolean pratik1 = test.contains('force');
            //system.debug('Cumlemizde force kelimesi var mi?:' + pratik1);
            //integer pratik2 = test.length();
            //system.debug('Cumledeki karakter sayisi:' + pratik2);
            //string pratik3 = test.toUpperCase();
            //system.debug('Cumlenin yeni hali:' + pratik3);
        
            //public void dateMethod(){
                //date bugun = date.today();
                //system.debug(bugun);
                //extra
                //datetime suAn = datetime.now();
                //system.debug(suAn);
                //datetime elliSaatSonra = suAn.addHours(50);
                //system.debug(elliSaatSonra);
            
        
        
        
        
        
  

  
        



    

