public  class SalesforceDeveloper {
    //public void myFirstCode(){
        //string myFavSehir = 'Mardin';
        //system.debug(myFavSehir);
        //string myFavFilm = 'Scarface';
        //system.debug(myFavFilm);
        //string myFavMevsim = 'Fall';
        //system.debug(myFavMevsim);

        public void myFavorites(){
            string myFavSehir = 'Mardin1';
            integer myFavNum = 7;
            system.debug('Favori numaram-->' + myFavNum+ ' '+ 've' +' Favori sehrim-->'+myFavSehir);
        }
    }
    

