//AccConAndOperations.opp_2('Web', 'Closed Won');
//system.debug(AccConAndOperations.opp_2('Web', 'Closed Won'));
//AccConAndOperations.accountOpp('Customer - Direct', 'Closed Won');
// system.debug('---------> '+AccConAndOppOperations.acc_1());
// system.debug('---------> '+AccConAndOppOperations.opp_2('Web','Closed Won'));
// string nameOppAcc= AccConAndOppOperations.accountOpp_1('Customer - Direct','Closed Won');
// system.debug(nameOppAcc);
// AccConAndOppOperations.accountOpp_1('Customer - Direct', 'Closed Won');
AccConAndOppOperations.createAcc(null, 2000000, 'prospect');